//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPWA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class briefcase
    {
        public int bc_id { get; set; }
        [Display(Name = "Nombre del proyecto")]
        public string proyect_name { get; set; }
        [Display(Name = "Rol")]
        public string proyect_rol { get; set; }
        [Display(Name = "Resumen")]
        public string summary { get; set; }
        [Display(Name = "Responsabilidades")]
        public string responsabilities { get; set; }
        [Display(Name = "Tecnologias utilizadas")]
        public string used_tech { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
