//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPWA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class certifications
    {
        public int cert_id { get; set; }
        [Display(Name = "Nombre de la certificación")]
        public string cert_name { get; set; }
        [Display(Name = "Institución")]
        public string cert_institution { get; set; }
        [Display(Name = "Descripción y objetivos")]
        public string cert_description { get; set; }
        [Display(Name = "Link de acceso")]
        public string cert_link { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
