//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPWA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.briefcase = new HashSet<briefcase>();
            this.certifications = new HashSet<certifications>();
            this.skills = new HashSet<skills>();
            this.work_experience = new HashSet<work_experience>();
        }
    
        public int user_id { get; set; }

        [Display(Name = "Nombre de usuario")]
        public string user_name { get; set; }
        [Display(Name = "Foto")]
        public string user_photo { get; set; }
        [Display(Name = "Nombre")]
        public string first_name { get; set; }
        [Display(Name = "Apellido")]
        public string last_name { get; set; }
        [Display(Name = "Correo eletrónico")]
        public string email { get; set; }
        [Display(Name = "Redes sociales")]
        public string social_net { get; set; }
        [Display(Name = "Introducción")]
        public string introduction { get; set; }
        [Display(Name = "Grado academico")]
        public string grade { get; set; }
        [Display(Name = "Profesión")]
        public string profession { get; set; }
        [Display(Name = "Universidad")]
        public string university { get; set; }
        [Display(Name = "Objetivos de la profesión")]
        public string grade_obj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<briefcase> briefcase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<certifications> certifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skills> skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_experience> work_experience { get; set; }
    }
}
