//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPWA
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class work_experience
    {   
        public int work_exp_id { get; set; }
        [Display(Name = "Experiencia laboral")]
        public string work_exp_description { get; set; }
        [Display(Name = "Fecha de inicio")]
        public Nullable<System.DateTime> date_init { get; set; }
        [Display(Name = "Fecha fin")]
        public Nullable<System.DateTime> date_fin { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual users users { get; set; }
    }
}
